INSERT INTO users (username, password, email, firstName, lastName, role) VALUES
  (
    'admin',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'biketrips.admin@gmail.com',
    'admin',
    'admin',
    'ADMIN'
  ),
  (
    'kacpkasp',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'kacp@kasp',
    'Kacper',
    'Kasprzyk',
    'MODER'
  ),
  (
    'irmikrys',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'irmi@krys',
    'Irmina',
    'Krysiak',
    'USER'
  ),
  (
    'rebirebi',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'rebi@rebi',
    'Rebecca',
    'Krysiak',
    'USER'
  ),
  (
    'test',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'test@test',
    'Test',
    'Test',
    'USER'
  ),
  (
    'user',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'user@user',
    'User',
    'User',
    'USER'
  ),
  (
    'user2',
    '$2a$10$MRFnsiGe3kSlF0lWALTu2e5e89heCXHFXHA2yuCIUuyyPRDNJ2/Cu',
    'user2@user2',
    'Usertwo',
    'Usertwo',
    'USER'
  );

INSERT INTO applications (username, email, isActive) VALUES
  (
    'irmikrys',
    'irmi@krys',
    true
  ),
  (
    'kacpkasp',
    'kacp@kasp',
    false
  ),
  (
    'rebirebi',
    'rebi@rebi',
    true
  );
